#LambdaEdge BY Anil

name: Deploy Lambda to CloudFront

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy Lambda function
        env:
          AWS_REGION: (region)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda create-function \
            --function-name <name of our lambda function> \
            --runtime nodejs14.x \
            --handler <handler-java-file>.<handler_function_of _our_exam_lambda_function> \
            --zip-file fileb://<Lambda_pack_path>.zip
          aws lambda update-function-code \
            --function-name <function_name> \
            --zip-file fileb://<Lambda_pack_path>.zip

      - name: Invalidate CloudFront cache
        env:
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id <cloudfront_distribution_id> \
            --paths "/*"
